data = input()
data = data.replace('hard', 'DespairSlope')
data = data.replace('sohungry', 'DiningHall')
data = data.replace('amazing', 'NanhuBuilding')
data = data.replace('sobeautiful', 'GuiziMountain')
data = data.replace('tired', 'YyBuilding')
data = data.replace('study', 'Library')
data = data.replace('toofast', 'SchoolBus')
print(data)
